### ISSUE TITLE
Epic 2.10 Text Rewriter

### ISSUE THREAD

**Issue by Ahmedr275** [marvelai-org/marvel-ai-backend#128]
# Develop Text Rewriter Tool

## Description

As an **educator**, I want to rewrite text based on specific instructions (e.g., simplify, summarize, or rephrase) so that I can adapt content for different reading levels, purposes, or contexts. This tool will help streamline the process of tailoring written material for diverse educational needs.

The tool should allow users to:  
- Input original text or upload files to be rewritten.  
- Provide rewriting instructions (e.g., simplify, summarize, rephrase).  
- Accept file uploads (one file per prompt) in supported formats:  
  - **Upload**: CSV, PDF, DOCX, PPT, Plain Text  
  - **URLs**: YouTube Video, Website, Google Sheets  
- Process the uploaded content and generate rewritten text tailored to the instructions.  
- Export the rewritten text in user-friendly formats such as plain text, DOCX, or PDF.

---
##Design
![Rewrite text](https://github.com/user-attachments/assets/6cdd1b02-d132-4ab4-b6ab-fa9295415528)
![Rewrite text-1](https://github.com/user-attachments/assets/6b1db6ac-9dc5-4aa8-b22d-1f3437214d0b)
![Generated Output](https://github.com/user-attachments/assets/8af4ed8d-b235-4a54-931f-619bceb56492)

#### **Input Handling**  
- [ ] Users can input **text to be rewritten** directly into a text box.  
- [ ] Users can upload files (**one file per prompt**) in the following formats:  
    - [ ] Upload: CSV, PDF, DOCX, PPT, Plain Text  
    - [ ] URLs: YouTube Video, Website, Google Sheets  
- [ ] Users can provide **rewriting instructions** via:  
    - [ ] Direct text input.  

#### **Text Rewriting Logic**  
- [ ] The tool rewrites the content based on:  
    - [ ] Provided instructions.  
    - [ ] Uploaded text or file input.  
- [ ] The rewritten text is aligned with the specified instruction and maintains original context and tone.

#### **Output Format**  
- [ ] The rewritten text is presented in a clear, editable format.  
- [ ] Users can export the rewritten text in the following formats:  
    - [ ] Plain Text  
    - [ ] DOCX  
    - [ ] PDF  

---

### **Folder Structure**  
- Create a new folder within `app/features/` named `text_rewriter`.

### **Core Development**  
- [ ] Implement the `executor` function in `core.py` with input parameters matching the tool's functionality, including type hints.  
- [ ] Use `tools.py` for abstractions and helper functions to keep `core.py` clean and maintainable.  
- [ ] Include a `metadata.json` file defining the input parameters for proper validation.  
- [ ] Utilize a `prompt/` folder for AI-driven generation prompts if necessary.  
- [ ] Implement logging and error handling as per platform standards.

### **Unit Tests**  
- [ ] Write unit tests for all functions and classes in `core.py` and `tools.py` using PyTest.  
    - [ ] Tests cover:  
        - [ ] Normal operation with valid inputs.  
        - [ ] Edge cases and invalid inputs.  
        - [ ] Error handling and exceptions.

### **Code Quality and Documentation**  
- [ ] Ensure code follows best practices for readability and maintainability.  
    - [ ] Use consistent naming conventions.  
    - [ ] Include type hints for all functions and methods.  
    - [ ] Avoid redundant or unnecessary code.  
- [ ] Add docstrings to all functions and classes explaining their purpose and usage.  
- [ ] Provide comments within the code where necessary to explain complex logic.

### **Integration and Testing**  
- [ ] Ensure the feature integrates seamlessly with the existing Marvel AI platform.  
    - [ ] The `executor` function is compatible with the `router.py` layer for request handling.  
    - [ ] Inputs are validated as per the platform's requirements.  
- [ ] Test the entire feature from input handling to output generation.  
    - [ ] Verify that users can input their data and receive the expected outputs without errors.

---

### **Input**  
**Original Text**:  
*"Romeo and Juliet is a tragic play by William Shakespeare that tells the story of two young lovers whose deaths ultimately reconcile their feuding families."*  

**Instruction**:  
- Simplify the text for a middle school audience.

### **Output**  
**Simplified Text**:  
*"Romeo and Juliet is a sad play by William Shakespeare about two young people who fall in love but die in the end, bringing peace to their fighting families."*

---

## Resources

1. [Design Mockup](https://www.figma.com/proto/lUJEUgY7DYLCJcx8db3CBK/Marvel---Live?node-id=5-5309&node-type=frame&t=vTMIf70WToOCv8g1-1&scaling=min-zoom&content-scaling=fixed&page-id=5%3A5308)

---

Please ensure that each of these criteria is fulfilled for the issue to be considered complete.

**Comment by ndubs18** [comment]
I would like to work on this issue

**Comment by timothydrew92** [comment]
FYI - I've started working on this issue if anyone has questions/comments/concerns : )

**Comment by arjun1998** [comment]
I have been going through resources and learning materials to soon start working on this

**Comment by DeveloperMindset123** [comment]
I will also be working on this issue as well as I continue to gain an understanding of the codebase.

**Comment by b53k** [comment]
Quick question. 

I kept getting this error "Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information." and found out it was because of API_Key set to None for some reason.

Later I added  the following in my core.py file and the issue was fixed. 

import os
from dotenv import load_dotenv, find_dotenv

dotenv_path = os.path.join(os.path.dirname(__file__), "../../../.env/.env")
load_dotenv(dotenv_path=dotenv_path)
api_key = os.getenv("GOOGLE_API_KEY")
os.environ["GOOGLE_API_KEY"] = api_key

Doing so, would it violate any documentation guideline? If this is not the correct way, can anyone correct me? Thanks.
(Apologies it this is a dumb question...I am new and still learning)

**Comment by AaronSosaRamos** [comment]
> Quick question.
> 
> I kept getting this error "Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information." and found out it was because of API_Key set to None for some reason.
> 
> Later I added the following in my core.py file and the issue was fixed.
> 
> import os from dotenv import load_dotenv, find_dotenv
> 
> dotenv_path = os.path.join(os.path.dirname(**file**), "../../../.env/.env") load_dotenv(dotenv_path=dotenv_path) api_key = os.getenv("GOOGLE_API_KEY") os.environ["GOOGLE_API_KEY"] = api_key
> 
> Doing so, would it violate any documentation guideline? If this is not the correct way, can anyone correct me? Thanks. (Apologies it this is a dumb question...I am new and still learning)

Hey @b53k. thank you for sharing your question. What you can do is:
1. Create an .env file inside of /app folder.
2. Set your GOOGLE_API_KEY inside of the .env
3. If there is a LLM call, you can use `load_dotenv(find_dotenv())` in that file (Not only in the main.py file)
4. Check if your GOOGLE_API_KEY is valid or if it is set correctly as your env. variable

Please, let me know if that worked for you.

**Comment by yangtom0516** [comment]
I will also be working on this issue

**Comment by AaronSosaRamos** [comment]
Hey @yangtom0516 , you can definitely pick up the issue and work on it. Our process for issue assignment is focused on first to PR so multiple contributors can work on an issue and can bring in their own improvements/ideas to the issue as well. Read more [here](https://lab.realityai.tech/posts/74703654)

**Comment by SehajpSingh** [comment]
Hello, I just onboarded and I would like to collaborate since its the good first issue. Please let me know if I am allowed to contribute still. Thanks

**Comment by yangtom0516** [comment]
@SehajpSingh We can work together if you want. My discord is tomyang

**Comment by ad-code1993** [comment]
Hey this is one my first open source project and I would like to collaborate with you guys

**Comment by AaronSosaRamos** [comment]
Hey @SehajpSingh @yangtom0516 @amanueldemirew , you can definitely pick up the issue and work on it. Our process for issue assignment is focused on first to PR so multiple contributors can work on an issue and can bring in their own improvements/ideas to the issue as well. Read more [here](https://lab.realityai.tech/posts/74703654)

**Comment by Flutevishnu** [comment]
Hi, can I start work on this issue?

**Comment by AaronSosaRamos** [comment]
Hey @Flutevishnu , you can definitely pick up the issue and work on it. Our process for issue assignment is focused on first to PR so multiple contributors can work on an issue and can bring in their own improvements/ideas to the issue as well. Read more [here](https://lab.realityai.tech/posts/74703654)

**Comment by aaryansingh-dev** [comment]
Hi @Flutevishnu, Can we connect and work on this together?

**Comment by Flutevishnu** [comment]
Hi @aaryansingh-dev , yes 

Which platform would you like discord or any other?

**Comment by aaryansingh-dev** [comment]
@Flutevishnu Discord works for me. My id is:  aaryan5130

**Comment by Flutevishnu** [comment]
@aaryansingh-dev i have sent you request , check it .
My id : _varadha

**Comment by Flutevishnu** [comment]
Should I create a new branch for a feature with the main branch (base) or develop branch ( base) 
by default it is develop  branch

**Comment by Sarang-Nambiar** [comment]
If the user does not provide any documents, and instead provides text in the rewrite textbox, would the content be passed to the backend as a text/html document or just as a different parameter to handle?

**Comment by Flutevishnu** [comment]
@Sarang-Nambiar  you can have different parameters. for reference  check lessonplan generator pipeline

**Comment by Flutevishnu** [comment]
@aaryansingh-dev does this feature needs a memory for previous reply ( rewritten text )

**Comment by aiyesha5128** [comment]
> Hi [@Flutevishnu](https://github.com/Flutevishnu), Can we connect and work on this together?

**Comment by maxLakhman** [comment]
Hello everyone, I'd like to start working on this. Would anyone like to connect and work on it with me?

**Comment by Passive-coder0** [comment]
> Hello everyone, I'd like to start working on this. Would anyone like to connect and work on it with me?

Let's do it!
join this whatsapp link: https://chat.whatsapp.com/ELpzVf4oC2tJSGcQJP5nRh

**Comment by Naaman233** [comment]
Can we utilize an LLM to handle the Text Rewriting or should we avoid using LLM's

**Comment by bhavana-11** [comment]
hello Everyone. I have just started this journey. I dont have prior professional experience in this, i hope you guys support me and guide me in this. And i would like to collaborate with anyone to learn and start the project.

**Comment by zhuoming34** [comment]
Hello everyone. I would like start on this to learn about the project. How far is everyone on this?

**Comment by D-Man2798** [comment]
hey guys, developer new to python here tackling this as one of my first open source contributions!

**Comment by yd-0413** [comment]
Hi guys, my name is Yalina. I just recently joined here and I would love to contribute in this project. Let me know if any of you would want to connect with me and collaborate on this project. Thanks.

**Comment by JunJie-Lai** [comment]
Hi, my name is Jun. Is there any ongoing on this issue progress that I can join? I only have experience in developing backend in Go, and foundational level in Python.
