### ISSUE TITLE
Epic 2.8 Worksheet Generator

### ISSUE THREAD

**Issue by mikhailocampo** [marvelai-org/marvel-ai-backend#53]
[Detailed Expedition Information](https://radicalxco.notion.site/Epic-7-3-1-Worksheet-Generator-5defe65e48d94f45ac62d0191410a7f3)

### Overview
This epic focuses on creating a worksheet for students based on various input sources such as Grade Level, question type(s), and Topic (or text). The goal is to provide educators with a custom generated worksheet which includes fill-in-the-blank or open-ended questions with an answer key provided at the end.

### Goals
- [ ] Create a new feature folder for the worksheet generator and an appropriate name
       - Create a `metadata.json` with the input parameters for the `executor`
       - Create a `core.py` with an appropriate `executor` function
       - Test the feature with a unit test and then a docker build 
- [ ] Document the feature such as expected inputs, outputs, and any tests done with langsmith
- [ ] Create a PR and add @mikhailocampo as the Reviewer
